version: '3.8'

services:
  mongo:
    image: mongo:6.0.4
    hostname: ${RS:-rs0}
    container_name: rs0
    command: mongod --replSet ${RS:-rs0} --port ${PORT:-27017}
    restart: always
    volumes:
      - ./data/db:/data/db
      - ./rs-init.sh:/scripts/rs-init.sh
    ports:
      - 27017:${PORT:-27017}